baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'HKU Student Union'
theme = 'HSU_HugoTheme'
sectionPagesMenu = "mainmenu"
favicon = "/favicon.io"
[taxonomies]
  category = 'categories'
  tag = 'tags'
[caches]
  [caches.images]
    dir = ':cacheDir/images'

